---
deployment:
 tasks:
 - export DEPLOYPATH=/home/upraythe5/public_html/
 - / index.html $DEPLOYPATH
 - / privacypolicy.html $DEPLOYPATH
  - /-R stylesheets $DEPLOYPATH/stylesheets
 - / -R images $DEPLOYPATH/images
